development:
  adapter: postgresql
  database: ldt_development
  pool: 5
  timeout: 5000
  port: 5432
  host: localhost
  username: postgres
  password: 168washu

test:
  adapter: postgresql
  database: ldt_test
  pool: 5
  timeout: 5000
  port: 5432
  host: localhost
  username: postgres
  password: 168washu

production:
  adapter: postgresql
  encoding: unicode
  database: ldt_production
  pool: 5
  username: ldt
  password:
